Structure generator: fcc + liquid

In [1]:
import numpy as np
import ase
import ase.io as lammpsdata
from ase import Atoms
from ase.visualize import view

In [2]:
import tqdm

In [3]:
fcc_a = 0.8442
n1 = 10
n2 = 10
n3 = 10
N_fluid = 1000

In [4]:
def cubic_structure(basis, n1, n2, n3, fcc_a):
    coordinates = []
    a1 = np.array([1,0,0])
    a2 = np.array([0,1,0])
    a3 = np.array([0,0,1])
    for i1 in range(n1):
        for i2 in range(n2):
            for i3 in range(n3):
                for initial in basis:
                    coordinates.append((a1*i1+a2*i2+a3*i3)*fcc_a + initial)
    return coordinates


In [5]:
def fluid_structure(basis, N, rmin, wall = [0,0,0]):
    coordinates = []
    N1 = int(wall[0]/rmin)
    N2 = int(wall[1]/rmin)
    N3 = int(wall[2]/rmin)
    N_full = N1*N2*N3
    N_choise = np.random.choice(N_full, N)
    N_current = 0
    for i1 in range(N1):
        for i2 in range(N2):
            for i3 in range(N3):
                if N_current in N_choise:
                    coordinates.append(basis+np.array([i1*rmin,i2*rmin,i3*rmin]))
                N_current+=1
    return coordinates

In [6]:
fcc_coordinates = cubic_structure(basis = [
                                 np.array([0,0,0]),
                                 np.array([0.5,0.5,0])*fcc_a,
                                 np.array([0.5,0,0.5])*fcc_a,
                                 np.array([0,0.5,0.5])*fcc_a],
                                 n1=n1,n2=n2,n3=n3,fcc_a=fcc_a 
                                  )

In [7]:
fluid_coordinates = fluid_structure(basis=np.array([n1+0.5,0,0]),
                                    N=N_fluid, 
                                    rmin=1, 
                                    wall = [n1*fcc_a, n2*fcc_a, n3*fcc_a])


In [8]:
full_coordinates = fcc_coordinates + fluid_coordinates

In [9]:
#full_coordinates
len(full_coordinates)

4437

In [11]:
h_positions = Atoms('H{:d}'.format(len(full_coordinates), position=full_coordinates))#, cell = [n1*fcc_a, n2*fcc_a])
view(h_positions, viewer="ngl")

In [21]:
########## working code from Teacher, (in you code coordinates are zero)
import numpy as np
fcc_a=0.8442/0.529
n1 = 10
n2 = 10
n3 = 10
N_fluid=500
rmin = 1.6
def cubic_structure(basis, n1, n2, n3, fcc_a):
    coordinates=[]
    a1 = np.array([1,0,0])
    a2 = np.array([0,1,0])
    a3 = np.array([0,0,1])
    for i1 in range(n1):
        for i2 in range(n2):
            for i3 in range(n3):
                for initial in basis:
                    coordinates.append(
                        (a1*i1 + a2*i2 + a3*i3 + initial)*fcc_a)
                    
    return coordinates

fcc_coordinates = cubic_structure(basis=[
                    np.array([0,0,0]),
                    np.array([0.5, 0.5, 0]),
                    np.array([0.5, 0, 0.5]),
                    np.array([0, 0.5, 0.5])],
                                  n1=n1, n2=n2, n3=n3, fcc_a=fcc_a)

def fluid_structure(basis, N, rmin, wall=[0,0,0]):
    coordinates = []
    N1 = int(wall[0]/rmin)
    N2 = int(wall[1]/rmin)
    N3 = int(wall[2]/rmin)
    N_full = N1*N2*N3
    print (N_full, N)
    N_choice=np.random.choice(N_full, N)
    N_current = 0
    for i1 in range(N1):
        for i2 in range(N2):
            for i3 in range(N3):
                if N_current in N_choice:
                    coordinates.append(basis+np.array([i1*rmin, i2*rmin, i3*rmin]))
                N_current += 1
    return coordinates

fluid_coordinates = fluid_structure(basis=np.array([n1+1,0,0])*fcc_a, 
                                           N=N_fluid, 
                                           rmin=rmin, 
                                           wall=[n1*fcc_a, n2*fcc_a, n3*fcc_a])
full_coordinates = fcc_coordinates + fluid_coordinates
from ase import Atoms
h_positions = Atoms('H{:d}O{:d}'.format(len(fcc_coordinates),len(fluid_coordinates)), positions=full_coordinates, cell=[n1*fcc_a*2, n2*fcc_a, n3*fcc_a], pbc=[1,1,1])
from ase.visualize import view
view(h_positions, viewer='ngl')

729 500


In [20]:
full_coordinates

[array([0., 0., 0.]),
 array([0.7979206, 0.7979206, 0.       ]),
 array([0.7979206, 0.       , 0.7979206]),
 array([0.       , 0.7979206, 0.7979206]),
 array([0.        , 0.        , 1.59584121]),
 array([0.7979206 , 0.7979206 , 1.59584121]),
 array([0.7979206 , 0.        , 2.39376181]),
 array([0.        , 0.7979206 , 2.39376181]),
 array([0.        , 0.        , 3.19168242]),
 array([0.7979206 , 0.7979206 , 3.19168242]),
 array([0.7979206 , 0.        , 3.98960302]),
 array([0.        , 0.7979206 , 3.98960302]),
 array([0.        , 0.        , 4.78752363]),
 array([0.7979206 , 0.7979206 , 4.78752363]),
 array([0.7979206 , 0.        , 5.58544423]),
 array([0.        , 0.7979206 , 5.58544423]),
 array([0.        , 0.        , 6.38336484]),
 array([0.7979206 , 0.7979206 , 6.38336484]),
 array([0.7979206 , 0.        , 7.18128544]),
 array([0.        , 0.7979206 , 7.18128544]),
 array([0.        , 0.        , 7.97920605]),
 array([0.7979206 , 0.7979206 , 7.97920605]),
 array([0.7979206 , 0

In [16]:
import ase.io as lammpsdata
lammpsdata.write("initial.lammps", h_positions,format=lammpsdata)

UnknownFileTypeError: <module 'ase.io' from '/home/common/studtscm03/anaconda3/lib/python3.9/site-packages/ase/io/__init__.py'>

In [18]:
# test nearest atoms
rcut = 0.5
n = len(full_coordinates)
for i1 in (range(n)):
    for i2 in range(i1+1,n):
        if (np.linalg.norm(full_coordinates[i1]-full_coordinates[i2])<rcut):
            print("dsdsddcd")

In [19]:
form ase.io

SyntaxError: invalid syntax (4025093089.py, line 1)